quarkus.application.name=dmca-calculator

# gRPC server port
quarkus.grpc.server.port=9000

# Embed rules resources in native image
quarkus.native.resources.includes=rules/**

# Logging
quarkus.log.level=INFO
quarkus.log.category."fr.dmca".level=DEBUG
